"""Added a validation to the restaurantpizza model

Revision ID: 39cec276fc5a
Revises: e8da71043b34
Create Date: 2024-02-04 10:40:43.460340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cec276fc5a'
down_revision = 'e8da71043b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
